### ISSUE TITLE
How to indicate timezone, or timezone offset?

### ISSUE THREAD

**Issue by brylie** [chfritz/meteor-easycron#9]
We have a server that is located in a different timezone than our primary users, and need to generate reports based on the users' timezone.

What timezone does easycron use by default, e.g. UTC? How can we build a cron job to run at midnight in a given timezone (e.g. UTC +2)?

**Comment by chfritz** [comment]
It runs on the server so it uses whatever timezone the server is using. It would probably be overkill to set a separate cron job for each user, so perhaps it would be best for you to just set an hourly cron job and then check for which users to create a report at that time? One way or another you'll need to write some separate logic for this. Since easycron is server based, it has no logic of users yet.
